/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 firstmug.gltf --transform
*/

// import React, { useRef } from 'react'
// import { useGLTF, PerspectiveCamera } from '@react-three/drei'

// export function Model(props) {
//   const { nodes, materials } = useGLTF('/firstmug.gltf')
//   return (
//     <group {...props} dispose={null}>
//       <PerspectiveCamera name="camera" fov={40} near={10} far={1000} position={[10,0,50]} />
//       <pointLight intensity={10} position={[100,50,100]} rotation={[-Math.PI / 2, 0, 0]} />
//       <group position={[10,-5,0]}>
//       <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.materials} />
//     </group>
//     </group>
//   )
// }

// useGLTF.preload('/firstmug.gltf')
